# Site settings
title: ant's blog
email: antwang1988@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  节制物欲，方能静心；心如止水，方得有成。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://antwang.github.io" # the base hostname & protocol for your site
twitter_username: antwang
github_username:  antwang

# Build settings
markdown: kramdown

# activate theme
theme: minima
